source 'https://rubygems.org'
gem 'rails', '~> 5.1'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.2'
gem 'jquery-rails'
gem 'haml'
gem 'nifty-utils', '~> 1.1'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey', '~> 1.0'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope'
gem 'florrick', '~> 1.1'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'

group :development, :test do
  gem 'annotate', '~> 2.6.5'
end
