source 'https://rubygems.org'
gem 'rails', '~> 4.2.6'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'haml', '~> 4.0.5'
gem 'nifty-utils', '~> 1.1'
gem 'nilify_blanks', '~> 1.1.0'
gem 'authie', '~> 1.1.0'
gem 'kaminari', '~> 0.16.1'
gem 'chronic', '~> 0.10.2'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt', '~> 3.1.7'
gem 'rails_env_config', '~> 1'
gem 'chronic_duration', '~> 0.10'
gem 'datey', '~> 1.0'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope', '~> 1.3'
gem 'florrick', '~> 1.1'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet', '~> 3.2.2'
gem 'premailer', '~> 1.8.3'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'annotate', '~> 2.6.5'
  gem 'pry-rails'
end
