default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

production:
  <<: *default
  database: statusd_production
  username: statusd
  password: <%= ENV['STATUSD_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: statusd_development

test:
  <<: *default
  database: statusd_test
