default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: statusd_database
  port: 3306

development:
  <<: *default
  database: statusd_development

test:
  <<: *default
  database: statusd_test
