# Database configuration for Staytus.
#
# By default, Staytus works with a MySQL database. While
# it may work with other engines, they are untested and
# currently unsupported. You can make changes to this file
# to specify the database to connect to.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: staytus
  host: 127.0.0.1

development:
  <<: *default

test:
  <<: *default
  database: staytus_test

production:
  adapter: mysql2
  encoding: utf8
  url: <%= ENV['JAWSDB_URL'] %>
