# Database configuration for Staytus.
#
# By default, Staytus works with a MySQL database. While
# it may work with other engines, they are untested and
# currently unsupported. You can make changes to this file
# to specify the database to connect to.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: statusd_development

test:
  <<: *default
  database: statusd_test
